# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jenny's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Jennifer Holt is a techincal writing living in Vancouver, BC
url: "https://bholtbholt.github.io/jennys-portfolio"
medium: https://medium.com/@jennypreswick
linkedin: https://www.linkedin.com/in/jennypreswick/

# Build settings
markdown: kramdown
theme: minima
port: 3000
safe: true

sass:
  style: compressed

collections:
  case-studies:
    output: true
    permalink: /:collection/:name
  writing:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      type: case-studies
    values:
      layout: collection
      order: 99
  -
    scope:
      type: writing
    values:
      layout: collection
      order: 99


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
